# PMINSREC - add all new files of the insurance card reconciliation to TFVC pending changes (model ACX)
# Run in "Developer PowerShell for VS" (tf.exe on PATH) from any folder inside the mapped workspace.
$base = "K:\AosService\PackagesLocalDirectory\ACX\ACX"
$files = @(
    "AxClass\PMINSRECCardImport.xml",
    "AxClass\PMINSRECFileFormatDefaults.xml",
    "AxClass\PMINSRECFileReader.xml",
    "AxClass\PMINSRECFormHelper.xml",
    "AxClass\PMINSRECIndividualReportImport.xml",
    "AxClass\PMINSRECJournalHelper.xml",
    "AxClass\PMINSRECProcessEngine.xml",
    "AxClass\PMINSRECReleaseManual.xml",
    "AxClass\PMINSRECSettleHelper.xml",
    "AxClass\PMINSRECSettlementBuilder.xml",
    "AxClass\PMINSRECSummaryReport.xml",
    "AxTable\PMINSRECCardImportLine.xml",
    "AxTable\PMINSRECCardSettlement.xml",
    "AxTable\PMINSRECFileFormat.xml",
    "AxTable\PMINSRECImportLog.xml",
    "AxTable\PMINSRECIndividualReport.xml",
    "AxTable\PMINSRECOutletSite.xml",
    "AxTable\PMINSRECParameters.xml",
    "AxTable\PMINSRECPostingSetup.xml",
    "AxTable\PMINSRECSummaryTmp.xml",
    "AxTableExtension\CustTable.PMINSREC.xml",
    "AxEdt\PMINSRECAccountNum.xml",
    "AxEdt\PMINSRECChassisNum.xml",
    "AxEdt\PMINSRECColumnName.xml",
    "AxEdt\PMINSRECDlrExecutive.xml",
    "AxEdt\PMINSRECEngineNum.xml",
    "AxEdt\PMINSRECFileName.xml",
    "AxEdt\PMINSRECOutletCode.xml",
    "AxEdt\PMINSRECPolicyNo.xml",
    "AxEdt\PMINSRECRegistrationNo.xml",
    "AxEdt\PMINSRECRequestId.xml",
    "AxEdt\PMINSRECText100.xml",
    "AxEdt\PMINSRECText255.xml",
    "AxEdt\PMINSRECText60.xml",
    "AxEdt\PMINSRECTransactionId.xml",
    "AxEnum\PMINSRECCardBank.xml",
    "AxEnum\PMINSRECCardField.xml",
    "AxEnum\PMINSRECDebitCredit.xml",
    "AxEnum\PMINSRECImportType.xml",
    "AxEnum\PMINSRECInsuranceType.xml",
    "AxEnum\PMINSRECReportGroupBy.xml",
    "AxEnum\PMINSRECStatus.xml",
    "AxForm\PMINSRECCardImportLine.xml",
    "AxForm\PMINSRECCardSettlement.xml",
    "AxForm\PMINSRECCustChassis.xml",
    "AxForm\PMINSRECFileFormat.xml",
    "AxForm\PMINSRECImportLog.xml",
    "AxForm\PMINSRECIndividualReport.xml",
    "AxForm\PMINSRECOutletSite.xml",
    "AxForm\PMINSRECParameters.xml",
    "AxForm\PMINSRECPostingSetup.xml",
    "AxForm\PMINSRECSummary.xml",
    "AxMenuItemDisplay\PMINSRECCardImportLine.xml",
    "AxMenuItemDisplay\PMINSRECCardSettlement.xml",
    "AxMenuItemDisplay\PMINSRECCustChassis.xml",
    "AxMenuItemDisplay\PMINSRECFileFormat.xml",
    "AxMenuItemDisplay\PMINSRECImportLog.xml",
    "AxMenuItemDisplay\PMINSRECIndividualReport.xml",
    "AxMenuItemDisplay\PMINSRECOutletSite.xml",
    "AxMenuItemDisplay\PMINSRECParameters.xml",
    "AxMenuItemDisplay\PMINSRECPostingSetup.xml",
    "AxMenuItemDisplay\PMINSRECSummary.xml",
    "AxMenuItemAction\PMINSRECCardImport.xml",
    "AxMenuItemAction\PMINSRECFileFormatDefaults.xml",
    "AxMenuItemAction\PMINSRECIndividualReportImport.xml",
    "AxMenuItemAction\PMINSRECProcess.xml",
    "AxMenuItemAction\PMINSRECReleaseManual.xml",
    "AxMenuItemAction\PMINSRECSummaryReport.xml",
    "AxMenu\PMINSRECInsuranceRecon.xml",
    "AxMenuExtension\MainMenu.PMINSREC.xml",
    "AxSecurityPrivilege\PMINSRECInsuranceReconMaintain.xml",
    "AxSecurityRole\PMINSRECInsuranceReconClerk.xml",
    "AxLabelFile\LabelResources\en-US\PMINSREC.en-US.label.txt",
    "AxLabelFile\PMINSREC_en-US.xml",
    "AxLabelFile\PMINSREC_en-IN.xml",
    "AxLabelFile\LabelResources\en-IN\PMINSREC.en-IN.label.txt"
)
$missing = $files | Where-Object { -not (Test-Path (Join-Path $base $_)) }
if ($missing) { Write-Host "Missing files (copy them first):" -ForegroundColor Red; $missing; return }
Push-Location $base
tf add $files /noprompt
Pop-Location
Write-Host "$($files.Count) files added to Pending Changes. Check in from Team Explorer > Pending Changes." -ForegroundColor Green
